# Generated by Django 2.2.5 on 2021-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clss',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snum',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='学号'),
        ),
    ]
