# Generated by Django 2.2.5 on 2021-03-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_check_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='method',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(default='正常上班', max_length=32, verbose_name='状态'),
        ),
    ]
